"""model name and manufacturer set not to be unique

Revision ID: 48bcd999aacc
Revises: 9c1f152d0451
Create Date: 2024-12-14 12:47:55.310563

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '48bcd999aacc'
down_revision: Union[str, None] = '9c1f152d0451'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('manufacturer', table_name='models')
    op.drop_index('name', table_name='models')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('name', 'models', ['name'], unique=True)
    op.create_index('manufacturer', 'models', ['manufacturer'], unique=True)
    # ### end Alembic commands ###
